
[package]
name = "rer"
version = { workspace = true }
description = "rer (\"Rez En Rust\") — command-line front-end for the Rust port of rez's solver."
edition = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rer"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
