[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0-rc.1"
authors = [
    "Lorenzo Montant <lo.montant.pro@gmail.com>",
    "Maxim Doucet <maxim.doucet@gmail.com>",
    "Philippe Llerena<philippe.llerena@gmail.com>",
    "Rémi Viette <remi.viette@gmail.com>",
]
edition = "2021"
description = "A rez implementation in rust"
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/doubleailes/rer"

[workspace.dependencies]
pubgrub = "0.3.0"
version-ranges = "0.1"
regex = "1.10.5"
lazy_static = "1.5.0"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rer-version = { path = "crates/rer-version", version = "0.1.0-rc.1" }
rer-resolver = { path = "crates/rer-resolver", version = "0.1.0-rc.1" }
uuid = { version = "1.9.1", features = ["v4", "fast-rng"] }
itertools = "0.13.0"
log = "0.4.20"
log4rs = { version = "1.2.0", features = ["gzip"] }
pyo3 = { version = "0.23.5", features = ["extension-module"] }
