[package]
name = "test-rust-python"
edition = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }

[lib]
name = "test_rust_python"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-parser = "0.3.1"
