[package]
name = "rer-resolver"
version = "0.0.1"
edition = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }

[lib]
name = "rer_resolver"

[dependencies]
pubgrub = { workspace = true }
version-ranges = { workspace = true }
rer-version = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
log = { workspace = true }
